version: "3.4"
services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    command:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --no-browser
      - --ServerApp.password=''
      - --ServerApp.token=''
      - --allow-root
